import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import SmoothScroll from "@/components/provider/SmoothScroll";
import { LenisProvider } from "@/components/provider/LenisSmoothScroll";
const inter = Inter({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900',] })

export const metadata: Metadata = {
  title: "Prospectiv",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={inter.className}
      >
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
