import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], weight: ['100','200','300','400', '500', '600', '700', '800','900',] })

const thicccboi = localFont({
  src:[
    {
      path: '../public/fonts/THICCCBOI-Thin.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-Black.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-Light.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-Regular.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-Medium.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-SemiBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-Bold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/THICCCBOI-ExtraBold.woff2',
      weight: '900',
      style: 'normal',
    }
  ],
  variable: "--font-thicccboi",
  display: "swap",
})


export const metadata: Metadata = {
  title: "Prospectiv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
